# Generated by Django 6.0 on 2025-12-18 04:16

import django.core.validators
import produtos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('notificar_promocao', models.BooleanField(default=True, help_text='Receber notificações quando este produto entrar em promoção', verbose_name='Notificar Promoção')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome completo do produto', max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto', verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, help_text='Descrição breve para listagens', max_length=255, null=True, verbose_name='Descrição Curta')),
                ('marca', models.CharField(help_text='Marca do produto', max_length=100, verbose_name='Marca')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto em R$', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, help_text='Preço com desconto (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço Promocional')),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade disponível', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('sku', models.CharField(blank=True, help_text='Código único do produto', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('seminovo', 'Seminovo'), ('recondicionado', 'Recondicionado')], default='novo', max_length=20, verbose_name='Estado do Produto')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso em quilogramas', max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('dimensoes', models.CharField(blank=True, help_text='Largura x Altura x Profundidade (cm)', max_length=100, null=True, verbose_name='Dimensões')),
                ('imagem_principal', models.ImageField(blank=True, help_text='Imagem principal do produto', null=True, upload_to=produtos.models.produto_imagem_path, verbose_name='Imagem Principal')),
                ('imagem_secundaria', models.ImageField(blank=True, help_text='Imagem adicional do produto', null=True, upload_to=produtos.models.produto_imagem_path, verbose_name='Imagem Secundária')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável para o produto', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('meta_titulo', models.CharField(blank=True, help_text='Título para SEO', max_length=255, null=True, verbose_name='Meta Título')),
                ('meta_descricao', models.TextField(blank=True, help_text='Descrição para SEO', null=True, verbose_name='Meta Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('em_promocao', models.BooleanField(default=False, verbose_name='Em Promoção')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('vendas', models.IntegerField(default=0, verbose_name='Quantidade Vendida')),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Média')),
                ('total_avaliacoes', models.IntegerField(default=0, verbose_name='Total de Avaliações')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoHistoricoPreco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco_antigo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Antigo')),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preço',
                'db_table': 'produto_historico_preco',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
