# Generated by Django 6.0 on 2025-12-18 20:59

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='Imagem principal do produto', null=True, upload_to=produtos.models.produto_imagem_path, verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, help_text='Imagem adicional do produto', null=True, upload_to=produtos.models.produto_imagem_path, verbose_name='Imagem Secundária'),
        ),
    ]
