# Generated by Django 6.0 on 2025-12-18 01:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(error_messages={'max_length': 'O nome não pode ter mais de 100 caracteres.', 'unique': 'Já existe uma categoria com este nome.'}, help_text='Nome da categoria (ex: Eletrônicos, Roupas)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da categoria', null=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, default='fas fa-tag', help_text='Classe do FontAwesome para ícone (ex: fas fa-mobile)', max_length=50, null=True, verbose_name='Ícone')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato HEX (#RRGGBB)', max_length=7, verbose_name='Cor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Se a categoria está ativa para uso', verbose_name='Ativa')),
                ('deletado', models.BooleanField(default=False, help_text='Se a categoria foi deletada (soft delete)', verbose_name='Deletada')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição da categoria (menor = primeiro)', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['nome'], name='categorias_nome_3b0a1e_idx'), models.Index(fields=['ativo'], name='categorias_ativo_c4d541_idx'), models.Index(fields=['ordem'], name='categorias_ordem_65dd10_idx')],
            },
        ),
    ]
