# Generated by Django 6.0 on 2025-12-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='categorias.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='produtohistoricopreco',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado Por'),
        ),
        migrations.AddField(
            model_name='produtohistoricopreco',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='produtos_nome_8fe6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['marca'], name='produtos_marca_74996d_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='produtos_categor_79cde9_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['preco'], name='produtos_preco_7f62fb_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['destaque'], name='produtos_destaqu_72468b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['em_promocao'], name='produtos_em_prom_0f464e_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='produtos_slug_571185_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['sku'], name='produtos_sku_85d141_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['publicado', 'deleted'], name='produtos_publica_284eda_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario', 'data_criacao'], name='favoritos_usuario_2ee93e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'produto')},
        ),
    ]
